---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    empty:
        format: "%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: empty
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 100
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 100
        encoding: utf8

    human_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: HUMAN
        formatter: simple
        filename: human.log
        maxBytes: 10485760 # 10MB
        backupCount: 100
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 100
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
...
