Agents:
  - number: 2
    file: conv.pkl
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {out_channels: 15, with_dealer: True}}
        - {class: ConvLstm, kwargs: {split_discarded: True}}
      optimizers:
        - {class: Adam, kwargs: {lr: 5.0e-5}}
        - {class: Adam, kwargs: {lr: 5.0e-4}}
      algorithms:
        - {class: AllRewards_Phase0, kwargs: {}}
        - {class: NStep_Phase1, kwargs: {n_step: , reward_data: 'offensive_defensive'}}
      policies:
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase1, kwargs: {}}}