Agents:
  - number: 2
    file: ./conv.pkl
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {out_channels: 5}}
        - {class: SimpleLSTM, kwargs: {}}
      optimizers:
        - {class: Adam, kwargs: {lr: 0.01}}
        - {class: Adam, kwargs: {lr: 0.005}}
      algorithms:
        - {class: TD0Phase0, kwargs: {}}
        - {class: TD0Phase1, kwargs: {}}
      policies:
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase1, kwargs: {}}}