Agents:
  - number: 2
    file: ./conv.pkl
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {out_channels: 5}}
        - {class: EvalPlays, kwargs: {}}
      optimizers:
        - {class: SGD, kwargs: {lr: 0.001}}
        - {class: SGD, kwargs: {lr: 0.001}}
      algorithms:
        - {class: AllRewards_Phase0, kwargs: {}}
        - {class: OneStep_Sarsa, kwargs: {}}
      policies:
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.05},
           callback: {name: choose_phase1, kwargs: {}}}
      training_settings:
        - {Start_epoch: 10}
        - {Start_epoch: 0}