Agents:
  - number: 2
    file: ./Train_agent_ConvLstm_10_102/Train_agent_ConvLstm_102.tar
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {out_channels: 5}}
        - {class: ConvLstm, kwargs: {}}
      optimizers:
        - {class: Adam, kwargs: {lr: 5.0e-6}}
        - {class: Adam, kwargs: {lr: 5.0e-4}}
      algorithms:
        - {class: AllRewards_Phase0, kwargs: {}}
        - {class: OneStep_Sarsa, kwargs: {}}
      policies:
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.025},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.025},
           callback: {name: choose_phase1, kwargs: {}}}