Agents:
  - number: 2
    file:
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {}}
        - {class: SimpleLSTM, kwargs: {}}
      optimizers:
        - {class: SGD, kwargs: {lr: 0.001}}
        - {class: SGD, kwargs: {lr: 0.001}}
      algorithms:
        - {class: TD0Phase0, kwargs: {}}
        - {class: TD0Phase1, kwargs: {}}
      policies:
        - {class: Boltzmann,
           kwargs: {tao: 1.0},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: Boltzmann,
           kwargs: {tao: 1.0},
           callback: {name: choose_phase1, kwargs: {}}}