Agents:
  - number: 2
    file: ./agents.tar
    kwargs:
      value_functions:
        - {class: Conv, kwargs: {}}
        - {class: LSTM, kwargs: {}}
      optimizers:
        - {class: Adam, kwargs: {lr: 0.00009}}
        - {class: Adam, kwargs: {lr: 0.00009}}
      algorithms:
        - {class: TD0Phase0, kwargs: {}}
        - {class: TD0Phase1, kwargs: {}}
      policies:
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.025},
           callback: {name: choose_phase0, kwargs: {}}}
        - {class: EpsilonGreedy,
           kwargs: {epsilon: 0.025},
           callback: {name: choose_phase1, kwargs: {}}}